name: frontend
description: "A new Flutter project."
publish_to: "none"

version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  go_router: ^17.0.0
  window_manager: ^0.5.1
  supabase_flutter: ^2.10.2
  font_awesome_flutter: ^10.10.0
  cached_network_image: ^3.2.3
  intl: ^0.20.2
  share_plus: ^12.0.1
  shared_preferences: ^2.5.3
  youtube_player_flutter: ^9.1.3
  flutter_inappwebview: ^6.0.0
  flutter_native_splash: ^2.4.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/images/logo.jpeg

flutter_native_splash:
  color: "#F1F3F4" # abu terang (light mode)
  image: assets/images/logo.jpeg

  color_dark: "#121212" # dark mode
  image_dark: assets/images/logo.jpeg

  android: true
  ios: true
  web: false

